load ../../systems/bank-account.maude
load ../../rltool.maude

set show advisories off .
set print attribute on .

(select BANK-ACCOUNT-stop .)
(use tool conrew  for validity         on BANK-ACCOUNT-DEFINEDOPS with FOFORMSIMPLIFY-IMP-IMPL .)
(use tool varsat  for unsatisfiability on FVP-NAT .)
(use tool varunif for varunif          on FVP-NAT .)

(declare-vars (A:Account) U (Msgs:MsgConf) U 
              (N:Nat) U (M:Nat) U (B:Bool) .)
(def-term-set (< bal: N pend: M overdraft: true > # Msgs) | true \/
              ([A,Msgs]) | true .)
(inv no-overdraft to '`[_`,_`] on
    (< bal: N pend: M overdraft: false > # Msgs) |
    (M <= N) = (true) /\ (debts(Msgs) <= M) = (true)
.)

(start-proof .)

--- INSERT PROOF SCRIPT HERE
(case 1 on Msgs&3:MsgConf by (Msg1:Msg, Msg2:MsgConf) U (mt) .)
(auto .)
(subsume 11 by 1 .) --- exists a substitution that seems to satisfy the TEUB |= thing in the subsumption formula
(auto .)
(auto .)
