load ../../systems/counter.maude
load ../../rltool-lib.maude

select RLTOOL-NOVU .
loop rltl-init .

set print conceal on .
print conceal mod_is_sorts_._____endm fmod_is_sorts_.____endfm .
set show advisories off .

(select COUNTER-EXAMPLE .)
(def-term-set ({0}) | true .)
(declare-vars (N:Nat) U (M:Nat) U (K:Nat) .)
(add-goal counter-dec : ({N + 1}) | (M < N + 1) = (true) => ({M}) | true .)
(start-proof .)
(auto .)
(subsume 14 by 13 .)
(case 13 on &3:Nat by (0) U (K + 1) .)
(replace 15 by (&4:Nat) = (0) .)
(split 16 by (&4:Nat < K:Nat + 1) = (true) and (K:Nat + 1) = (&4:Nat) .)
(auto .)
(auto .)
(auto .)
quit .
